# ROOT_ANIMATOR_NAME = 1001
ROOT_ANIMATOR_NAME = "DYNOBJ_MARIO_MAIN_ANIMATOR"

# DYNOBJ_MARIO_MAIN_NET = 221
DYNOBJ_MARIO_MAIN_NET = "DYNOBJ_MARIO_MAIN_NET"

# DYNOBJ_MARIO_MAIN_SHAPES_GROUP = 1000
DYNOBJ_MARIO_MAIN_SHAPES_GROUP = "DYNOBJ_MARIO_MAIN_SHAPES_GROUP"
